services:

  # ==========================================================
  # MODBUS
  # ==========================================================

  modbus:
    image: nquangkhanh/datalogger-modbus:1.0
    container_name: datalogger-modbus
    restart: unless-stopped

    environment:
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5000:5000"

    volumes:
      - ./RuntimeData:/app/RuntimeData

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"


  # ==========================================================
  # DATABASE
  # ==========================================================

  database:
    image: nquangkhanh/datalogger-database:1.0
    container_name: datalogger-database
    restart: unless-stopped

    environment:
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5001:5001"

    volumes:
      - ./RuntimeData:/app/RuntimeData

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"


  # ==========================================================
  # MQTT
  # ==========================================================

  mqtt:
    image: nquangkhanh/datalogger-mqtt:1.0
    container_name: datalogger-mqtt
    restart: unless-stopped

    environment:
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5003:5003"

    volumes:
      - ./RuntimeData:/app/RuntimeData

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"


  # ==========================================================
  # FTP
  # ==========================================================

  ftp:
    image: nquangkhanh/datalogger-ftp:1.0
    container_name: datalogger-ftp
    restart: unless-stopped

    environment:
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5002:5002"

    volumes:
      - ./RuntimeData:/app/RuntimeData

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"